'use client';

import { useEffect, useState, useRef } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { motion } from 'framer-motion';
import { ArrowLeft, Download, Share2, Eye, Edit3 } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { createClient } from '@/lib/supabase/client';
import type { Project, PlanData, AnalysisScores } from '@/types';
import { cn } from '@/lib/utils';

const PLAN_SECTIONS = [
  { key: 'overview', title: 'サービス概要', icon: '📋' },
  { key: 'targetMarket', title: 'ターゲット市場', icon: '🎯' },
  { key: 'valueProposition', title: '提供価値', icon: '💎' },
  { key: 'competitors', title: '競合・差別化', icon: '⚔️' },
  { key: 'revenueModel', title: '収益モデル', icon: '💰' },
  { key: 'milestones', title: 'マイルストーン', icon: '🚀' },
] as const;

export default function PlanPage() {
  const params = useParams();
  const router = useRouter();
  const projectId = params.id as string;

  const [project, setProject] = useState<Project | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  const supabase = createClient();

  useEffect(() => {
    async function fetchProject() {
      const { data, error } = await supabase
        .from('projects')
        .select('*')
        .eq('id', projectId)
        .single();

      if (error || !data) {
        router.push('/dashboard');
        return;
      }

      setProject(data as Project);
      setIsLoading(false);
    }

    fetchProject();
  }, [projectId, router, supabase]);

  const handleDownloadPDF = async () => {
    if (!project?.plan_data) return;

    setIsGeneratingPDF(true);

    try {
      // Dynamic import to avoid SSR issues
      const { jsPDF } = await import('jspdf');

      const doc = new jsPDF();
      const planData = project.plan_data as PlanData;
      const scores = project.analysis_scores as AnalysisScores | null;

      // Set font for Japanese support (using built-in fonts)
      doc.setFont('helvetica');

      // Title
      doc.setFontSize(24);
      doc.setTextColor(12, 133, 241);
      doc.text(planData.serviceName || 'Business Plan', 20, 30);

      // Subtitle
      doc.setFontSize(12);
      doc.setTextColor(100, 116, 139);
      doc.text('Business Plan Document', 20, 40);
      doc.text(`Generated: ${new Date().toLocaleDateString('ja-JP')}`, 20, 48);

      // Divider
      doc.setDrawColor(226, 232, 240);
      doc.line(20, 55, 190, 55);

      let yPos = 70;

      // Sections
      PLAN_SECTIONS.forEach((section) => {
        const content = planData[section.key as keyof PlanData];

        if (yPos > 250) {
          doc.addPage();
          yPos = 30;
        }

        // Section title
        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.text(`${section.icon} ${section.title}`, 20, yPos);
        yPos += 8;

        // Section content
        doc.setFontSize(11);
        doc.setTextColor(71, 85, 105);

        const text = content || 'Not specified';
        const lines = doc.splitTextToSize(text, 170);
        doc.text(lines, 20, yPos);
        yPos += lines.length * 6 + 15;
      });

      // Add scores if available
      if (scores) {
        if (yPos > 200) {
          doc.addPage();
          yPos = 30;
        }

        doc.setFontSize(14);
        doc.setTextColor(15, 23, 42);
        doc.text('📊 Analysis Scores', 20, yPos);
        yPos += 10;

        doc.setFontSize(11);
        doc.setTextColor(71, 85, 105);

        const scoreLabels = {
          feasibility: 'Feasibility',
          marketSize: 'Market Size',
          innovation: 'Innovation',
          profitability: 'Profitability',
          scalability: 'Scalability',
          teamFit: 'Team Fit',
        };

        Object.entries(scores).forEach(([key, value]) => {
          const label = scoreLabels[key as keyof typeof scoreLabels];
          doc.text(`${label}: ${value}/100`, 20, yPos);
          yPos += 7;
        });

        const avgScore = Math.round(
          Object.values(scores).reduce((a, b) => a + b, 0) / Object.values(scores).length
        );
        yPos += 5;
        doc.setFontSize(12);
        doc.setTextColor(12, 133, 241);
        doc.text(`Overall Score: ${avgScore}/100`, 20, yPos);
      }

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(9);
        doc.setTextColor(148, 163, 184);
        doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
        doc.text('Generated by Loopin - AI Business Partner', 105, 295, {
          align: 'center',
        });
      }

      // Save
      doc.save(`${planData.serviceName || 'business-plan'}.pdf`);
    } catch (error) {
      console.error('PDF generation error:', error);
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  if (isLoading || !project) {
    return (
      <div className="h-screen flex items-center justify-center">
        <motion.div
          className="w-16 h-16 border-4 border-primary-500 border-t-transparent rounded-full"
          animate={{ rotate: 360 }}
          transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
        />
      </div>
    );
  }

  const planData = project.plan_data as PlanData | null;

  return (
    <div className="min-h-screen bg-slate-50/50 py-8 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <motion.div
          className="flex items-center justify-between mb-8"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
        >
          <div className="flex items-center gap-4">
            <Link href={`/project/${projectId}`}>
              <Button variant="ghost" size="sm" leftIcon={<ArrowLeft className="w-4 h-4" />}>
                戻る
              </Button>
            </Link>
            <div>
              <h1 className="text-2xl font-bold text-slate-900">事業計画書</h1>
              <p className="text-slate-600">{project.title}</p>
            </div>
          </div>

          <div className="flex gap-2">
            <Link href={`/project/${projectId}`}>
              <Button variant="secondary" size="sm" leftIcon={<Edit3 className="w-4 h-4" />}>
                編集
              </Button>
            </Link>
            <Button
              onClick={handleDownloadPDF}
              isLoading={isGeneratingPDF}
              leftIcon={<Download className="w-4 h-4" />}
            >
              PDF出力
            </Button>
          </div>
        </motion.div>

        {!planData ? (
          <motion.div
            className="text-center py-20"
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
          >
            <div className="w-20 h-20 bg-slate-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
              <Edit3 className="w-10 h-10 text-slate-400" />
            </div>
            <h2 className="text-xl font-semibold text-slate-700 mb-2">
              計画書が未作成です
            </h2>
            <p className="text-slate-500 mb-6">
              AIとの壁打ちを通じて計画書を作成してください
            </p>
            <Link href={`/project/${projectId}`}>
              <Button>壁打ちを始める</Button>
            </Link>
          </motion.div>
        ) : (
          <div className="space-y-6">
            {/* Title Card */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
            >
              <Card className="bg-gradient-to-r from-primary-500 to-accent-500 text-white">
                <CardContent className="p-8">
                  <motion.h2
                    className="text-3xl font-bold mb-2"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.2 }}
                  >
                    {planData.serviceName || 'New Project'}
                  </motion.h2>
                  <p className="text-white/80">
                    事業計画書 • {new Date().toLocaleDateString('ja-JP')}
                  </p>
                </CardContent>
              </Card>
            </motion.div>

            {/* Plan Sections */}
            {PLAN_SECTIONS.map((section, index) => {
              const content = planData[section.key as keyof PlanData];

              return (
                <motion.div
                  key={section.key}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: index * 0.1 }}
                >
                  <Card>
                    <CardHeader>
                      <CardTitle className="flex items-center gap-3">
                        <span className="text-2xl">{section.icon}</span>
                        {section.title}
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      {content ? (
                        <p className="text-slate-700 whitespace-pre-wrap leading-relaxed">
                          {content}
                        </p>
                      ) : (
                        <p className="text-slate-400 italic">未入力</p>
                      )}
                    </CardContent>
                  </Card>
                </motion.div>
              );
            })}

            {/* Analysis Scores Summary */}
            {project.analysis_scores && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.6 }}
              >
                <Card>
                  <CardHeader>
                    <CardTitle className="flex items-center gap-3">
                      <span className="text-2xl">📊</span>
                      分析スコア
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                      {Object.entries(project.analysis_scores as AnalysisScores).map(
                        ([key, value]) => {
                          const labels: Record<string, string> = {
                            feasibility: '実現可能性',
                            marketSize: '市場規模',
                            innovation: '革新性',
                            profitability: '収益性',
                            scalability: '成長性',
                            teamFit: 'チーム適合',
                          };

                          return (
                            <div
                              key={key}
                              className="text-center p-3 bg-slate-50 rounded-xl"
                            >
                              <p className="text-2xl font-bold text-primary-600">
                                {value}
                              </p>
                              <p className="text-xs text-slate-500 mt-1">
                                {labels[key]}
                              </p>
                            </div>
                          );
                        }
                      )}
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
